-- Paira Marketplace - PostgreSQL / Supabase Setup

-- TABLES

CREATE TABLE Users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role VARCHAR(20) NOT NULL
        CHECK (role IN ('Admin', 'Seller', 'Customer'))
);

CREATE TABLE Category (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL
);

CREATE TABLE Product (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    image_url VARCHAR(255),
    price NUMERIC(10,2) NOT NULL,
    stock INTEGER DEFAULT 0 CHECK (stock >= 0),
    seller_id INTEGER NOT NULL,
    category_id INTEGER,

    FOREIGN KEY (seller_id)
        REFERENCES Users(user_id)
        ON DELETE CASCADE,

    FOREIGN KEY (category_id)
        REFERENCES Category(category_id)
        ON DELETE SET NULL
);

CREATE TABLE Orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_amount NUMERIC(10,2) DEFAULT 0,

    FOREIGN KEY (customer_id)
        REFERENCES Users(user_id)
        ON DELETE CASCADE
);

CREATE TABLE OrderDetails (
    od_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL,
    product_id INTEGER,
    product_name VARCHAR(100),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(10,2) NOT NULL,

    FOREIGN KEY (order_id)
        REFERENCES Orders(order_id)
        ON DELETE CASCADE,

    FOREIGN KEY (product_id)
        REFERENCES Product(product_id)
        ON DELETE SET NULL
);

CREATE TABLE Cart (
    cart_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER UNIQUE NOT NULL,

    FOREIGN KEY (customer_id)
        REFERENCES Users(user_id)
        ON DELETE CASCADE
);

CREATE TABLE CartItems (
    cart_id INTEGER,
    product_id INTEGER,
    quantity INTEGER NOT NULL CHECK (quantity > 0),

    PRIMARY KEY (cart_id, product_id),

    FOREIGN KEY (cart_id)
        REFERENCES Cart(cart_id)
        ON DELETE CASCADE,

    FOREIGN KEY (product_id)
        REFERENCES Product(product_id)
        ON DELETE CASCADE
);

CREATE TABLE Payment (
    payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER UNIQUE NOT NULL,
    amount NUMERIC(10,2) NOT NULL,

    status VARCHAR(50) DEFAULT 'Pending'
        CHECK (status IN ('Pending', 'Paid', 'Failed', 'Refunded')),

    payment_method VARCHAR(50) DEFAULT 'Cash',
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (order_id)
        REFERENCES Orders(order_id)
        ON DELETE CASCADE
);

CREATE TABLE Review (
    review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,

    rating INTEGER CHECK (rating BETWEEN 1 AND 5),

    review_text VARCHAR(500),
    review_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id)
        REFERENCES Users(user_id)
        ON DELETE CASCADE,

    FOREIGN KEY (product_id)
        REFERENCES Product(product_id)
        ON DELETE CASCADE
);

CREATE TABLE BrowsingHistory (
    history_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id)
        REFERENCES Users(user_id)
        ON DELETE CASCADE,

    FOREIGN KEY (product_id)
        REFERENCES Product(product_id)
        ON DELETE CASCADE
);

-- STOCK UPDATE TRIGGER

CREATE OR REPLACE FUNCTION update_product_stock()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE Product
    SET stock = stock - NEW.quantity
    WHERE product_id = NEW.product_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_stock
AFTER INSERT ON OrderDetails
FOR EACH ROW
EXECUTE FUNCTION update_product_stock();

-- SAMPLE DATA

INSERT INTO Users (user_id, name, email, password, role)
VALUES
(1, 'Areeba', 'areeba@gmail.com', 'pbkdf2:sha256:600000$2ed3352a754770f6$b65f6dc31493cf69256220458f7baddc2516455428f9da972709ca39b8176b63', 'Customer'),
(2, 'Ali Seller', 'ali@gmail.com', 'pbkdf2:sha256:600000$2ed3352a754770f6$b65f6dc31493cf69256220458f7baddc2516455428f9da972709ca39b8176b63', 'Seller'),
(3, 'Admin', 'admin@gmail.com', 'pbkdf2:sha256:600000$7e66aa6965f57c9d$7571a523378f6662f3f33edb00bfed11eb73fbb748615a6c651836ee1dee3265', 'Admin');

INSERT INTO Category (category_id, category_name)
VALUES
(1, 'Bags'),
(2, 'Shoes');

INSERT INTO Product
(product_id, name, description, image_url, price, stock, seller_id, category_id)
VALUES
(1, 'Handbag',
 'Stylish leather handbag',
 '',
 2500, 10, 2, 1),

(2, 'Purple Handbag',
 'Stylish leather handbag purple color',
 '',
 2700, 12, 2, 1),

(3, 'Shoulder Bag',
 'Stylish leather shoulder bag',
 '',
 3000, 10, 2, 1),

(4, 'Tote Bag',
 'Stylish leather tote bag',
 '',
 2700, 12, 2, 1),

(5, 'Sneakers',
 'Comfortable everyday sneakers',
 '',
 5000, 5, 2, 2);

INSERT INTO Cart (cart_id, customer_id)
VALUES (1, 1);

INSERT INTO CartItems (cart_id, product_id, quantity)
VALUES (1, 1, 2);

INSERT INTO Orders
(order_id, customer_id, order_date, total_amount)
VALUES
(1, 1, CURRENT_TIMESTAMP, 2500);

INSERT INTO OrderDetails
(od_id, order_id, product_id, product_name, quantity, unit_price)
VALUES
(1, 1, 1, 'Handbag', 1, 2500);

INSERT INTO Payment
(payment_id, order_id, amount, status, payment_method, payment_date)
VALUES
(1, 1, 2500, 'Paid', 'Cash', CURRENT_TIMESTAMP);

INSERT INTO Review
(review_id, user_id, product_id, rating, review_text, review_date)
VALUES
(1, 1, 1, 5, 'Great product!', CURRENT_TIMESTAMP);

-- RESET IDENTITY COUNTERS AFTER MANUAL SAMPLE IDs

SELECT setval(
    pg_get_serial_sequence('users', 'user_id'),
    (SELECT MAX(user_id) FROM Users)
);

SELECT setval(
    pg_get_serial_sequence('category', 'category_id'),
    (SELECT MAX(category_id) FROM Category)
);

SELECT setval(
    pg_get_serial_sequence('product', 'product_id'),
    (SELECT MAX(product_id) FROM Product)
);

SELECT setval(
    pg_get_serial_sequence('orders', 'order_id'),
    (SELECT MAX(order_id) FROM Orders)
);

SELECT setval(
    pg_get_serial_sequence('orderdetails', 'od_id'),
    (SELECT MAX(od_id) FROM OrderDetails)
);

SELECT setval(
    pg_get_serial_sequence('cart', 'cart_id'),
    (SELECT MAX(cart_id) FROM Cart)
);

SELECT setval(
    pg_get_serial_sequence('payment', 'payment_id'),
    (SELECT MAX(payment_id) FROM Payment)
);

SELECT setval(
    pg_get_serial_sequence('review', 'review_id'),
    (SELECT MAX(review_id) FROM Review)
);

-- VIEWS

CREATE VIEW SellerDashboard AS
SELECT
    u.name AS seller,
    COUNT(DISTINCT p.product_id) AS total_products,
    COALESCE(SUM(od.quantity * od.unit_price), 0) AS total_sales,
    COALESCE(ROUND(AVG(r.rating), 1), 0) AS avg_rating

FROM Users u

LEFT JOIN Product p
    ON u.user_id = p.seller_id

LEFT JOIN OrderDetails od
    ON p.product_id = od.product_id

LEFT JOIN Review r
    ON p.product_id = r.product_id

WHERE u.role = 'Seller'

GROUP BY u.name;

CREATE VIEW AdminOrderOverview AS
SELECT
    o.order_id,
    u.name AS customer,
    o.order_date,
    o.total_amount,
    pay.status AS payment_status,
    pay.payment_method

FROM Orders o

JOIN Users u
    ON o.customer_id = u.user_id

JOIN Payment pay
    ON o.order_id = pay.order_id;

-- SUPABASE API EXPOSURE
-- Paira uses a server-side PostgreSQL connection. The browser does not
-- query these tables through the Supabase Data API.
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
